# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build your Remix.js application
RUN npm run build

# Expose the port that your Remix.js application will run on (default is 3000)
EXPOSE 3000

# Start your Remix.js application when the container starts
CMD ["npm", "start"]
